# Generated by Django 5.1.2 on 2025-11-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='otp_phoneot_phone_n_6a5014_idx',
            old_name='otp_phone_purpose_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='otp_phoneot_session_500638_idx',
            old_name='otp_session_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='otp_phoneot_expires_293129_idx',
            old_name='otp_expires_idx',
        ),
    ]
