version: '3.8'

services:
  web:
    build: .
    container_name: fire_alarm_app
    ports:
      - "6066:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    # Load environment variables for secrets and config
    env_file:
      - .env
