# Generated by Django 5.1.2 on 2025-09-26 16:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hardware_identifier', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alert_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('smoke_level', models.IntegerField()),
                ('device_status', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user'], name='devices_dev_user_id_624f27_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['hardware_identifier'], name='devices_dev_hardwar_7c234d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', 'status'], name='devices_ale_device__b09c79_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_at'], name='devices_ale_trigger_786c47_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['device', 'timestamp'], name='devices_tel_device__82fcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['received_at'], name='devices_tel_receive_bd99e8_idx'),
        ),
    ]
