# Generated by Django 5.1.2 on 2025-09-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-registered_at']},
        ),
    ]
