# Generated by Django 5.1.2 on 2025-09-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-triggered_at']},
        ),
    ]
