# Generated by Django 5.1.2 on 2025-09-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_master_slave_model"),
    ]

    operations = []
