# Generated by Django 5.1.2 on 2025-09-28 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_devices_de_device_r_0e1aa2_idx_devices_dev_device__9d803f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_role'], name='devices_dev_device__9d803f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['master'], name='devices_dev_master__bef140_idx'),
        ),
    ]
