# Generated by Django 5.1.2 on 2025-10-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_devices_dev_device__9d803f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-last_seen', '-registered_at']},
        ),
    ]
