# Generated by Django 5.1.2 on 2025-11-18 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alert_enhancements_and_alarm_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='last_triggered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devicealarmstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='devicealarmstate',
            index=models.Index(fields=['next_reminder_at'], name='devices_dev_next_re_da65d0_idx'),
        ),
    ]
