# Generated by Django 5.1.2 on 2025-11-18 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_alert_last_triggered_at_and_more'),
        ('products', '0007_order_assigned_devices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='originating_order',
            field=models.ForeignKey(blank=True, help_text='Order that supplied this physical device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='products.order'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['originating_order'], name='devices_dev_origina_8c4aa1_idx'),
        ),
    ]
