# Generated by Django 5.1.2 on 2025-11-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_originating_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
