# Generated by Django 5.1.2 on 2025-12-01 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_device_registered_at'),
        ('products', '0009_alter_order_number_of_slave_devices_orderfulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Package assigned to this device (for admin-registered devices without an order)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='products.package'),
        ),
    ]
