# Generated by Django 5.1.2 on 2025-12-09 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_add_package_to_device'),
        ('products', '0011_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['hardware_identifier', 'deleted_at'], name='devices_dev_hardwar_d6d133_idx'),
        ),
    ]
