# Generated by Django 5.1.2 on 2025-12-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_add_composite_index_hardware_deleted'),
        ('resellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='reseller',
            field=models.ForeignKey(blank=True, help_text='Reseller who sold this device to the end user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_devices', to='resellers.reseller'),
        ),
    ]
