# Generated by Django 5.1.2 on 2025-11-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firestations', '0002_firestation_name_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='firestation',
            new_name='firestation_distric_fd9255_idx',
            old_name='firestatio_distric_05a695_idx',
        ),
        migrations.RenameIndex(
            model_name='firestation',
            new_name='firestation_distric_583ea6_idx',
            old_name='firestatio_distric_099364_idx',
        ),
    ]
