# Generated by Django 5.1.2 on 2025-11-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('company_admin', 'Company Admin'), ('superadmin', 'Super Admin')], default='user', max_length=16),
        ),
    ]
