# Generated by Django 5.1.2 on 2025-12-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_unique_phone_number'),
        ('resellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reseller',
            field=models.ForeignKey(blank=True, help_text='Reseller who acquired this user as a customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_users', to='resellers.reseller'),
        ),
    ]
