# Generated by Django 5.1.2 on 2025-12-17 21:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, help_text="Brand name shown to reseller's customers (if different from company name)", max_length=255)),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], db_index=True, default='pending', max_length=16)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage reseller earns on sales (0-100)', max_digits=5)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage on bulk purchases (0-100)', max_digits=5)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum credit allowed for this reseller', max_digits=12)),
                ('current_credit_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current credit balance used', max_digits=12)),
                ('logo_url', models.URLField(blank=True, help_text="URL to reseller's logo")),
                ('primary_color', models.CharField(blank=True, help_text='Primary brand color in hex (e.g., #FF5733)', max_length=7)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain for white-label access', max_length=255)),
                ('max_devices', models.PositiveIntegerField(default=0, help_text='Maximum devices this reseller can have in total (0 = unlimited)')),
                ('max_customers', models.PositiveIntegerField(default=0, help_text='Maximum customers this reseller can have (0 = unlimited)')),
                ('agreement_signed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this reseller')),
                ('admin_user', models.OneToOneField(help_text='The company_admin user who manages this reseller', on_delete=django.db.models.deletion.PROTECT, related_name='reseller_account', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer_reference', models.CharField(blank=True, help_text="Reseller's internal customer reference/ID", max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='resellers.reseller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hardware_identifier', models.CharField(db_index=True, max_length=64)),
                ('device_role', models.CharField(choices=[('master', 'Master'), ('slave', 'Slave')], default='master', max_length=10)),
                ('master_hardware_identifier', models.CharField(blank=True, help_text='For slave devices, the hardware ID of their master', max_length=64, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price reseller paid for this device', max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned'), ('defective', 'Defective')], db_index=True, default='available', max_length=16)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price charged to end customer', max_digits=10, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(help_text='The order when reseller purchased this device', on_delete=django.db.models.deletion.PROTECT, related_name='reseller_inventory_items', to='products.order')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='resellers.reseller')),
                ('sold_to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_inventory_items', to='resellers.resellercustomer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reseller Inventories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Amount before reseller discount', max_digits=12)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Amount after discount', max_digits=12)),
                ('is_credit_purchase', models.BooleanField(default=False, help_text='Whether this was purchased on credit')),
                ('credit_due_date', models.DateField(blank=True, null=True)),
                ('credit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reseller_purchase', to='products.order')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='resellers.reseller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate at time of sale', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Calculated commission for this sale', max_digits=12)),
                ('commission_paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='resellers.resellercustomer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='resellers.reseller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reseller',
            index=models.Index(fields=['status'], name='resellers_r_status_435537_idx'),
        ),
        migrations.AddIndex(
            model_name='reseller',
            index=models.Index(fields=['admin_user'], name='resellers_r_admin_u_b5d600_idx'),
        ),
        migrations.AddIndex(
            model_name='reseller',
            index=models.Index(fields=['company_name'], name='resellers_r_company_7b69a1_idx'),
        ),
        migrations.AddIndex(
            model_name='resellercustomer',
            index=models.Index(fields=['reseller', 'user'], name='resellers_r_reselle_3ec1db_idx'),
        ),
        migrations.AddIndex(
            model_name='resellercustomer',
            index=models.Index(fields=['customer_reference'], name='resellers_r_custome_6ed482_idx'),
        ),
        migrations.AddConstraint(
            model_name='resellercustomer',
            constraint=models.UniqueConstraint(fields=('reseller', 'user'), name='unique_customer_per_reseller'),
        ),
        migrations.AddIndex(
            model_name='resellerinventory',
            index=models.Index(fields=['reseller', 'status'], name='resellers_r_reselle_790cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerinventory',
            index=models.Index(fields=['hardware_identifier'], name='resellers_r_hardwar_12a29a_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerinventory',
            index=models.Index(fields=['sold_to_customer'], name='resellers_r_sold_to_b40496_idx'),
        ),
        migrations.AddConstraint(
            model_name='resellerinventory',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['available', 'reserved'])), fields=('hardware_identifier', 'reseller'), name='unique_active_inventory_per_reseller'),
        ),
        migrations.AddIndex(
            model_name='resellerpurchaseorder',
            index=models.Index(fields=['reseller'], name='resellers_r_reselle_fcbc70_idx'),
        ),
        migrations.AddIndex(
            model_name='resellersale',
            index=models.Index(fields=['reseller'], name='resellers_r_reselle_fce119_idx'),
        ),
        migrations.AddIndex(
            model_name='resellersale',
            index=models.Index(fields=['customer'], name='resellers_r_custome_0b7226_idx'),
        ),
    ]
