# Generated by Django 5.1.2 on 2025-11-18 07:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0011_device_originating_order_and_more'),
        ('products', '0008_backfill_order_assigned_devices'),
        ('shurjopay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('billing_anchor', models.DateTimeField()),
                ('last_paid_through', models.DateTimeField()),
                ('next_due_at', models.DateTimeField()),
                ('grace_expires_at', models.DateTimeField(blank=True, null=True)),
                ('admin_override_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='devices.device')),
                ('originating_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='products.order')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=191)),
                ('payload_snapshot', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_charges', to='shurjopay.paymenttransaction')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='subscriptions.devicesubscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='devicesubscription',
            index=models.Index(fields=['status'], name='subscriptio_status_c17fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesubscription',
            index=models.Index(fields=['next_due_at'], name='subscriptio_next_du_26bcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesubscription',
            index=models.Index(fields=['grace_expires_at'], name='subscriptio_grace_e_b26a82_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['status'], name='subscriptio_status_53b329_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['period_end'], name='subscriptio_period__d74441_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncharge',
            unique_together={('subscription', 'period_start', 'period_end')},
        ),
    ]
