# Generated by Django 5.1.2 on 2025-11-18 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_backfill_device_subscriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncharge',
            name='cycles',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of billing cycles covered by this charge'),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='manual_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_subscription_charges', to=settings.AUTH_USER_MODEL),
        ),
    ]
