# Generated by Django 5.1.2 on 2025-11-05
import hashlib
from django.db import migrations, models


def drop_registration_token_unique(apps, schema_editor):
    table = apps.get_model("notifications", "FCMDevice")._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, table
        )
    for name, info in constraints.items():
        columns = info.get("columns") or []
        if info.get("unique") and columns == ["registration_token"]:
            schema_editor.execute(
                f"ALTER TABLE {schema_editor.quote_name(table)} "
                f"DROP INDEX {schema_editor.quote_name(name)}"
            )
            break


def drop_registration_token_hash_column(apps, schema_editor):
    table = apps.get_model("notifications", "FCMDevice")._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        existing_cols = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table
            )
        }
    if "registration_token_hash" in existing_cols:
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table)} "
            f"DROP COLUMN {schema_editor.quote_name('registration_token_hash')}"
        )


def drop_registration_token_index(apps, schema_editor):
    table = apps.get_model("notifications", "FCMDevice")._meta.db_table
    index_name = "notificatio_registr_5a2094_idx"
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, table
        )
    if index_name in constraints:
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table)} "
            f"DROP INDEX {schema_editor.quote_name(index_name)}"
        )


def populate_token_hash(apps, schema_editor):
    FCMDevice = apps.get_model("notifications", "FCMDevice")
    for device in FCMDevice.objects.all().iterator():
        token = getattr(device, "registration_token", "") or ""
        token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
        FCMDevice.objects.filter(pk=device.pk).update(
            registration_token_hash=token_hash
        )


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            drop_registration_token_hash_column,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            drop_registration_token_index,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            drop_registration_token_unique,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="fcmdevice",
            name="registration_token_hash",
            field=models.CharField(
                default="",
                editable=False,
                max_length=64,
                help_text="Hash of the FCM registration token (ensures uniqueness)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fcmdevice",
            name="registration_token",
            field=models.CharField(
                max_length=1024,
                help_text="FCM registration token from the mobile app",
            ),
        ),
        migrations.RunPython(populate_token_hash, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="fcmdevice",
            name="registration_token_hash",
            field=models.CharField(
                editable=False,
                max_length=64,
                unique=True,
                help_text="Hash of the FCM registration token (ensures uniqueness)",
            ),
        ),
    ]
