# Generated by Django 5.1.2 on 2025-11-18 09:47

from django.db import migrations


def drop_registration_token_index(apps, schema_editor):
    table = apps.get_model("notifications", "FCMDevice")._meta.db_table
    index_name = "notificatio_registr_5a2094_idx"
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, table
        )
    if index_name in constraints:
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table)} "
            f"DROP INDEX {schema_editor.quote_name(index_name)}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_remove_fcmdevice_notificatio_registr_5a2094_idx"),
    ]

    atomic = False

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_registration_token_index,
                    migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="fcmdevice",
                    name="notificatio_registr_5a2094_idx",
                )
            ],
        )
    ]
