# Generated by Django 5.1.2 on 2025-12-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shurjopay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Unique key to prevent duplicate payment attempts', max_length=64, null=True, unique=True),
        ),
    ]
