# Generated by Django 5.1.2 on 2025-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='mrt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly recurring fee (MRF) for this package', max_digits=10),
        ),
    ]
