# Generated by Django 5.1.2 on 2025-10-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_total_amount_order_amount_order_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='mrt',
            new_name='mrf',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
