# Generated by Django 5.1.2 on 2025-10-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_mrt_package_mrf_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_master_devices',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_slave_devices',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=16),
        ),
    ]
