# Generated by Django 5.1.2 on 2025-11-18 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_updated_at_order_updated_by_package_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_devices',
            field=models.PositiveIntegerField(default=0, help_text='Number of device registrations already linked to this order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_devices'], name='products_or_assigne_9751a2_idx'),
        ),
    ]
