# Generated by Django 5.1.2 on 2025-11-22 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_backfill_order_assigned_devices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_of_slave_devices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware_identifier', models.CharField(max_length=64, unique=True)),
                ('device_role', models.CharField(choices=[('master', 'Master'), ('slave', 'Slave')], default='master', max_length=10)),
                ('master_hardware_identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='products.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['hardware_identifier'], name='products_or_hardwar_0acf1f_idx'), models.Index(fields=['order', 'is_claimed'], name='products_or_order_i_38788a_idx')],
            },
        ),
    ]
