# Generated by GitHub Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_ecommerce_improvements"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "Online"), ("cod", "Cash on Delivery")],
                default="online",
                max_length=16,
            ),
        ),
    ]
